# Generated by Django 5.2.6 on 2025-12-10 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('idArtista', models.TextField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('url', models.URLField(verbose_name='URL')),
                ('pictureUrl', models.URLField(verbose_name='Picture URL')),
            ],
            options={
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('idTag', models.TextField(primary_key=True, serialize=False)),
                ('tagValue', models.TextField(verbose_name='Tag Value')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioArtista',
            fields=[
                ('idUsuario', models.TextField(verbose_name='Id del usuario')),
                ('tiempoEscucha', models.IntegerField(primary_key=True, serialize=False)),
                ('idArtista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artista')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEtiquetaArtista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.TextField(verbose_name='Id del usuario')),
                ('fecha', models.DateField(verbose_name='Fecha de escucha')),
                ('idArtista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artista')),
                ('idTagValue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.etiqueta')),
            ],
        ),
    ]
