# Generated by Django 5.2.6 on 2025-12-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioartista',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='artista',
            name='nombre',
            field=models.TextField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuarioartista',
            name='tiempoEscucha',
            field=models.IntegerField(),
        ),
    ]
